#!/usr/bin/env python3
"""Quine-McCluskey minimization for W-bit addition SOP tables (W=1..4).
Writes:
  include/cud/compute_lib/add_table.h
  src/cud/compute_lib/add_table.cpp
"""

import os, sys

# ── Quine-McCluskey ───────────────────────────────────────────────────────────

def quine_mccluskey(minterms, num_vars):
    if not minterms:
        return []
    def to_imp(m):
        return tuple((m >> i) & 1 for i in range(num_vars))
    current = {to_imp(m): frozenset([m]) for m in minterms}
    prime_implicants = {}
    while current:
        next_round = {}
        used = set()
        imps = list(current.keys())
        for i in range(len(imps)):
            for j in range(i + 1, len(imps)):
                a, b = imps[i], imps[j]
                same_nones = all((a[k] is None) == (b[k] is None) for k in range(num_vars))
                if not same_nones:
                    continue
                diffs = [k for k in range(num_vars)
                         if a[k] is not None and a[k] != b[k]]
                if len(diffs) == 1:
                    combined = list(a); combined[diffs[0]] = None; combined = tuple(combined)
                    covered = current[a] | current[b]
                    if combined in next_round:
                        next_round[combined] |= covered
                    else:
                        next_round[combined] = covered
                    used.add(i); used.add(j)
        for i, imp in enumerate(imps):
            if i not in used and imp not in prime_implicants:
                prime_implicants[imp] = current[imp]
        current = next_round
    return list(prime_implicants.items())

def minimal_cover(minterms, pis):
    if not minterms:
        return []
    mset = set(minterms)
    coverage = {m: [] for m in mset}
    for idx, (imp, cov) in enumerate(pis):
        for m in cov:
            if m in coverage:
                coverage[m].append(idx)
    chosen = set()
    covered = set()
    for m, ps in coverage.items():
        if len(ps) == 1:
            chosen.add(ps[0])
    for i in chosen:
        covered |= pis[i][1] & mset
    remaining = mset - covered
    while remaining:
        best = max(range(len(pis)), key=lambda i: len(pis[i][1] & remaining))
        chosen.add(best); remaining -= pis[best][1]
    return [pis[i][0] for i in chosen]

# ── SOP computation ───────────────────────────────────────────────────────────

def add_sop(W):
    """Returns list of W+1 expressions.
    Each expression: sorted list of terms.
    Each term: sorted list of (var_idx, is_neg).
      var_idx in [0,W):  a[var_idx]
      var_idx in [W,2W): b[var_idx-W]
    """
    num_vars = 2 * W
    result = []
    for out_bit in range(W + 1):
        minterms = []
        for idx in range(1 << num_vars):
            a = idx & ((1 << W) - 1)
            b = (idx >> W) & ((1 << W) - 1)
            if ((a + b) >> out_bit) & 1:
                minterms.append(idx)
        if not minterms:
            result.append([]); continue
        pis = quine_mccluskey(minterms, num_vars)
        cover = minimal_cover(minterms, pis)
        terms = []
        for imp in cover:
            lits = [(vi, val == 0) for vi, val in enumerate(imp) if val is not None]
            terms.append(tuple(sorted(lits)))
        result.append(sorted(terms))
    return result

# ── C++ emission ──────────────────────────────────────────────────────────────

HEADER = """\
// Auto-generated by scripts/gen_add_tables.py — do not edit.
#pragma once
#include <cstdint>

// Literal: one bit-plane of a bit-serial input.
//   var < W  → a[var],   neg=false → a-positive, neg=true → ~a
//   var >= W → b[var-W], neg=false → b-positive, neg=true → ~b
struct AddLit { uint8_t var; bool neg; };

// One product term (AND of n literals).
struct AddTerm { uint8_t n; AddLit lits[8]; };

// One output-bit expression (OR of n terms).
// Largest case: c3 of 4-bit adder has 36 terms.
struct AddBitExpr { uint8_t n; AddTerm terms[64]; };

// kAdderSop[W-1][out_bit], W in [1..4], out_bit in [0..W].
// kAdderSop[W-1] has W+1 valid entries; remaining slots are zero.
extern const AddBitExpr kAdderSop[4][5];
"""

def bool_str(b):
    return "true" if b else "false"

def emit_lit(var, neg):
    return f"AddLit{{{var}, {bool_str(neg)}}}"

def emit_term(lits):
    lits_str = ", ".join(emit_lit(v, n) for v, n in lits)
    return f"AddTerm{{{len(lits)}, {{{lits_str}}}}}"

def emit_bit_expr(terms):
    if not terms:
        return "AddBitExpr{0, {}}"
    term_strs = ", ".join(emit_term(t) for t in terms)
    return f"AddBitExpr{{{len(terms)}, {{{term_strs}}}}}"

def emit_cpp(max_W=4):
    lines = [
        "// Auto-generated by scripts/gen_add_tables.py — do not edit.",
        '#include "cud/compute_lib/add_table.h"',
        "",
        "const AddBitExpr kAdderSop[4][5] = {",
    ]
    for W in range(1, max_W + 1):
        sop = add_sop(W)
        total_terms = sum(len(t) for t in sop)
        total_lits  = sum(sum(len(t2) for t2 in t) for t in sop)
        lines.append(f"  // W={W}: {total_terms} terms, {total_lits} literals total")
        lines.append("  {")
        for out_bit in range(5):
            if out_bit > W:
                lines.append("    {0, {}},  // padding")
            else:
                terms = sop[out_bit]
                comment = f"// c{out_bit}: {len(terms)} terms"
                lines.append(f"    {emit_bit_expr(terms)},  {comment}")
        lines.append("  },")
    lines.append("};")
    return "\n".join(lines)

# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    h_path   = os.path.join(repo_root, "include", "cud", "compute_lib", "add_table.h")
    cpp_path = os.path.join(repo_root, "src", "cud", "compute_lib", "add_table.cpp")

    # Print summary
    for W in range(1, 5):
        sop = add_sop(W)
        total = sum(len(t) for t in sop)
        lits  = sum(sum(len(t2) for t2 in t) for t in sop)
        print(f"W={W}: {total} terms, {lits} literals")
        for k, terms in enumerate(sop):
            print(f"  c{k}: {len(terms)} terms")

    # Write files
    with open(h_path, "w") as f:
        f.write(HEADER)
    with open(cpp_path, "w") as f:
        f.write(emit_cpp())

    print(f"\nWrote {h_path}")
    print(f"Wrote {cpp_path}")
