// Auto-generated by scripts/gen_add_tables.py — do not edit.
#pragma once
#include <cstdint>

// Literal: one bit-plane of a bit-serial input.
//   var < W  → a[var],   neg=false → positive, neg=true → complemented
//   var >= W → b[var-W], neg=false → positive, neg=true → complemented
struct AddLit  { uint8_t var; bool neg; };

// One product term (AND of n literals, n <= 16).
struct AddTerm { uint8_t n; AddLit lits[16]; };

// One output-bit expression (OR of n terms, n <= 1024).
struct AddBitExpr { uint16_t n; AddTerm terms[1024]; };

// kAdderSop[W-1][out_bit], W in [1..8], out_bit in [0..W].
// kAdderSop[W-1] has W+1 valid entries; remaining slots are zero-padded.
extern const AddBitExpr kAdderSop[8][9];
