// Auto-generated by scripts/gen_add_tables.py — do not edit.
#pragma once
#include <cstdint>

// Literal: one bit-plane of a bit-serial input.
//   var < W  → a[var],   neg=false → a-positive, neg=true → ~a
//   var >= W → b[var-W], neg=false → b-positive, neg=true → ~b
struct AddLit { uint8_t var; bool neg; };

// One product term (AND of n literals).
struct AddTerm { uint8_t n; AddLit lits[8]; };

// One output-bit expression (OR of n terms).
// Largest case: c3 of 4-bit adder has 36 terms.
struct AddBitExpr { uint8_t n; AddTerm terms[64]; };

// kAdderSop[W-1][out_bit], W in [1..4], out_bit in [0..W].
// kAdderSop[W-1] has W+1 valid entries; remaining slots are zero.
extern const AddBitExpr kAdderSop[4][5];
